default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: remind_me_ok_development
  username: postgres
  password: postroot

test:
  <<: *default
  database: remind_me_ok_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 2 } %> # Adjusted for low-resource environment
  timeout: 5000